# Generated by Django 4.2.4 on 2023-08-25 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_date_menu_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='event',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
