# Generated by Django 4.2.4 on 2023-08-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_user_alter_food_rating_alter_menu_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='suggestionboard',
            old_name='post_id',
            new_name='id',
        ),
    ]
