# Generated by Django 4.2.4 on 2023-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
