# Generated by Django 4.2.4 on 2023-08-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_rating_delete_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
