# Generated by Django 4.2.4 on 2023-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menu_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
