# Generated by Django 4.2.4 on 2023-08-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_menu_rating_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='menu',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
