# Generated by Django 4.2.4 on 2023-09-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_review_menu_review_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='created_at',
            new_name='date',
        ),
    ]
