# Generated by Django 4.2.4 on 2023-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_rename_created_at_menu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
