# Generated by Django 4.2.4 on 2023-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurant_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='avg_rating',
        ),
    ]
